spring:
  messages:
    basename: exceptions
  cloud:
    stream:
      bindings:
        output:
          destination: departments
          content-type: application/json
security:
  oauth2:
    resource:
      filter-order: 3