version: '3.3'
services:
  kafka_server:
    image: spotify/kafka
    ports:
      - "2181"
      - "9092"
    environment:
      - TOPICS=departments
      - ADVERTISED_HOST=${KAFKA_SERVER}
      - ADVERTISED_PORT=9092
    networks:
      cloud:
        ipv4_address: ${KAFKA_SERVER}
  configuration_server:
    image: training/configuration
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - DEFAULT_PROFILE=${DEFAULT_PROFILE}
      - PING_TIMEOUT=${PING_TIMEOUT}
    networks:
      cloud:
        ipv4_address: ${CONFIGURATION_SERVER}
  discovery_server:
    image: training/discovery
    ports:
    - 8001:8080
    environment:
    - ENCRYPT_KEY=${ENCRYPT_KEY}
    - PING_TIMEOUT=${PING_TIMEOUT}
    - CONFIGURATION_SERVER_URI=${CONFIGURATION_SERVER_URI}
    - DEFAULT_PORT=${DEFAULT_PORT}
    - CONFIGURATION_SERVER_PORT=${CONFIGURATION_SERVER_PORT}
    networks:
      cloud:
        ipv4_address: ${DISCOVERY_SERVER}
networks:
  cloud:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}